apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: roboshop
  labels: # these labels belong to deployment
    app: mysql
    tier: db
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels: # these labels should match with pod
      app: mysql
      tier: db
      project: roboshop
  template: # this is the pod definition
    metadata:
      labels:
        app: mysql
        tier: db
        project: roboshop
    spec:
      containers:
      - name: mysql
        image: visu90522/mysql:1.0.0
        envFrom:
        - configMapRef:
            name: mysql
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: roboshop
spec:
  selector:
    app: mysql
    tier: db
    project: roboshop
  ports:
  - name: mysql-port
    protocol: TCP
    port: 3306 # this port belongs to service
    targetPort: 3306 # this port belongs to container
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql
  namespace: roboshop
data:
  MYSQL_ALLOW_EMPTY_PASSWORD: "yes" # keep true in double quotes
  MYSQL_DATABASE: "cities"
  MYSQL_USER: "shipping"
  MYSQL_PASSWORD: "RoboShop@1"